# Generated by Django 2.2 on 2021-11-16 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211116_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='type_of',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='app.AdvertisementType'),
        ),
    ]
