# Generated by Django 2.2 on 2021-11-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
