# Generated by Django 2.2 on 2022-04-18 19:04

import app_stock.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('date_start', models.DateField(auto_now_add=True, verbose_name='date start')),
                ('date_end', models.DateField(verbose_name='date end')),
                ('discount', models.IntegerField(validators=[app_stock.validators.max_min_value])),
            ],
        ),
    ]
