# Generated by Django 2.2 on 2022-06-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
                ('publicated_at', models.DateTimeField(auto_now_add=True, verbose_name='publicated at')),
            ],
        ),
    ]
