# Generated by Django 4.0.6 on 2022-07-10 10:45

import app_profile.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0002_auto_20220625_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=app_profile.tools.get_path),
        ),
    ]
