# Generated by Django 4.0.6 on 2022-07-18 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telephon_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(regex='+\\d{11}')], verbose_name='telephone number'),
        ),
    ]
