# Generated by Django 4.0.6 on 2022-07-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0006_profile_telephon_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telephon_number',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='telephone number'),
        ),
    ]
