# Generated by Django 4.0.6 on 2022-07-20 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0008_alter_profile_telephon_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telephon_number',
            field=models.CharField(blank=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(regex='\\+\\d{11}')], verbose_name='telephon number'),
        ),
    ]
