# Generated by Django 4.0.6 on 2022-07-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0009_alter_profile_telephon_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='city'),
        ),
    ]
