# Generated by Django 4.1 on 2022-08-12 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0037_product_free_delivery_product_is_exist'),
        ('app_profile', '0011_profile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.ManyToManyField(to='app_shop.order', verbose_name='orders')),
                ('profile', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_profile.profile', verbose_name='profile')),
            ],
        ),
    ]
