# Generated by Django 4.1 on 2022-08-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0013_profile_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card',
            field=models.CharField(blank=True, max_length=8, verbose_name='card'),
        ),
    ]
