# Generated by Django 4.1 on 2022-08-25 18:04

import app_profile.tools
import app_profile.validators
import app_shop.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0014_alter_profile_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=app_profile.tools.get_path, validators=[app_profile.validators.validate_image], verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='card',
            field=models.CharField(blank=True, max_length=8, validators=[app_shop.validators.validate_card_even, django.core.validators.RegexValidator(regex='\\d{4} \\d{4}')], verbose_name='card'),
        ),
    ]
