# Generated by Django 2.2 on 2022-06-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0004_auto_20220614_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristic',
            field=models.TextField(blank=True, verbose_name='characteristic'),
        ),
    ]
