# Generated by Django 2.2 on 2022-06-15 16:39

import app_shop.utility
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_product_characteristic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='title')),
            ],
            bases=(app_shop.utility.StrMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='app_shop.Tag', verbose_name='tag(s)'),
        ),
    ]
