# Generated by Django 2.2 on 2022-06-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0007_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='other_characteristic',
            field=models.TextField(blank=True, verbose_name='other characteristic'),
        ),
    ]
