# Generated by Django 4.0.6 on 2022-07-11 20:25

import app_shop.tools
import app_shop.utility
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0011_auto_20220619_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=170, unique=True, verbose_name='title')),
                ('image', models.ImageField(upload_to=app_shop.tools.get_path, verbose_name='image')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_shop.product', verbose_name='product')),
            ],
            bases=(app_shop.utility.StrMixin, models.Model),
        ),
    ]
