# Generated by Django 4.0.6 on 2022-07-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0012_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='title',
            field=models.CharField(blank=True, max_length=170, unique=True, verbose_name='title'),
        ),
    ]
