# Generated by Django 4.0.6 on 2022-07-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0013_alter_productimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='content_image',
            field=models.BooleanField(default=False, verbose_name='content image'),
        ),
    ]
