# Generated by Django 4.0.6 on 2022-07-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0014_productimage_content_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
    ]
