# Generated by Django 4.0.6 on 2022-07-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0016_product_images_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
    ]
