# Generated by Django 4.0.6 on 2022-07-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0020_productcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.ManyToManyField(related_name='comments', to='app_shop.productcomment', verbose_name='comment(s)'),
        ),
    ]
