# Generated by Django 4.0.6 on 2022-07-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0025_productstorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstorage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_shop.category', verbose_name='product'),
        ),
    ]
