# Generated by Django 4.0.6 on 2022-07-22 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0009_alter_profile_telephon_number'),
        ('app_shop', '0028_alter_productstorage_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='count')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_shop.product', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_profile.profile', verbose_name='customer')),
                ('product_order', models.ManyToManyField(to='app_shop.productorder', verbose_name='product order')),
            ],
        ),
    ]
