# Generated by Django 4.0.6 on 2022-07-23 13:05

import app_shop.utility
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0029_productorder_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMPTT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='title')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_shop.categorymptt')),
            ],
            options={
                'abstract': False,
            },
            bases=(app_shop.utility.StrMixin, models.Model),
        ),
    ]
