# Generated by Django 4.0.6 on 2022-07-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0032_remove_order_customer_order_address_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.CharField(blank=True, choices=[('ONLINE', 'online'), ('SOMEONE', 'someone')], max_length=10, null=True),
        ),
    ]
