# Generated by Django 4.0.6 on 2022-07-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0033_order_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivary',
            field=models.CharField(blank=True, choices=[('ORDINARY', 'ordinary'), ('EXPRESS', 'express')], max_length=10, null=True),
        ),
    ]
