# Generated by Django 4.0.6 on 2022-08-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0034_order_delivary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivary',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, choices=[('ORDINARY', 'ordinary'), ('EXPRESS', 'express')], max_length=10, null=True),
        ),
    ]
