# Generated by Django 4.0.6 on 2022-08-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0035_remove_order_delivary_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymptt',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='slug'),
        ),
    ]
