# Generated by Django 4.1 on 2022-08-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0037_product_free_delivery_product_is_exist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_proce',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='total price'),
        ),
    ]
