# Generated by Django 4.1 on 2022-08-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0039_rename_total_proce_order_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
