# Generated by Django 4.1 on 2022-08-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0041_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card',
            field=models.CharField(blank=True, max_length=8, verbose_name='card'),
        ),
    ]
