# Generated by Django 4.1 on 2022-08-25 18:04

import app_shop.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0042_order_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(regex='\\d{4} \\d{4}'), app_shop.validators.validate_card_even], verbose_name='card'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='images', to='app_shop.productimage', verbose_name='image(s)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='app_shop.tag', verbose_name='tag(s)'),
        ),
    ]
