# Generated by Django 4.1 on 2022-08-26 08:15

import app_shop.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0043_alter_order_card_alter_product_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymptt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app_shop.tools.get_path, verbose_name='image'),
        ),
    ]
