# Generated by Django 4.1 on 2022-08-28 08:36

import app_shop.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0054_alter_categorymptt_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.AlterField(
            model_name='categorymptt',
            name='image',
            field=models.FileField(blank=True, default='app_shop/categories/Electronics_gpKEGby.svg', null=True, upload_to=app_shop.tools.get_path_category, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
