# Generated by Django 4.1 on 2022-08-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0055_remove_product_tag_alter_categorymptt_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPriceForDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinary_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='ordinary_price')),
                ('express_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='express_price')),
            ],
        ),
    ]
