# Generated by Django 4.1 on 2022-08-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0056_orderpricefordelivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpricefordelivery',
            name='express_price',
        ),
        migrations.RemoveField(
            model_name='orderpricefordelivery',
            name='ordinary_price',
        ),
        migrations.AddField(
            model_name='orderpricefordelivery',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='orderpricefordelivery',
            name='title',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='title'),
        ),
    ]
