# Generated by Django 2.2 on 2022-04-22 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('BEGINNER', 'beginner'), ('ADVANCED', 'advanced'), ('EXPERT', 'expert')], max_length=3, verbose_name='title')),
            ],
            options={
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.AlterField(
            model_name='moderator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='author',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_blog.Status', verbose_name='status'),
        ),
    ]
